project/project/urls.py
# from django.contrib import admin
# from django.urls import path, include
from django.contrib import admin
from django.urls import path , include,re_path
from django.conf import settings
from django.conf.urls.static import static

from fundproject.views import home 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', home,name='home'),
    path('project/', include('fundproject.urls')),
    path('fundapi/', include('fundapi.urls')),
    re_path('^', include('django.contrib.auth.urls')),


]
# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import include, path, re_path


from users.views import register, user_login, activate, index
from django.conf import settings
from django.conf.urls.static import static
from users import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetConfirmView
from .views import userprofile
from rest_framework import routers
from .views import usersListView
app_name = 'users'
router = routers.DefaultRouter()
router.register(r'usersListView', usersListView)

urlpatterns = [

    path('register/', views.register , name='register'),
    path('activate/<uidb64>/<time>',views.activate, name='activate'),
    path('login/', views.user_login , name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('userprofile', views.userprofile  , name="userprofile"),
    path('deleteprofile/<int:id>' , views.deleteprofile , name="deleteprofile"),
    path('editprofile/<int:id>' , views.editprofile , name="editprofile"),
    path('userproject/<int:id>' , views.userproject , name="userproject"),
    path('userdonation/<int:id>' , views.userdonation , name="userdonation"),
    path('users', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('logout/',views.logout_view,name='logout'),
    #  path('profile',views.user_profile,name="profile"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_reset/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_reset/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset/password_change.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset/password_reset_form.html'), name='password_reset'),


    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset/password_reset_complete.html'),
     name='password_reset_complete'),

    re_path('^', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>
    {%block Title%}
    Crowd Funding
    {% endblock %}
  </title>
  {%load static%}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  



  {% block head-css %}
  <link rel="stylesheet" type="text/css" href="{% static '' %}">
  <link rel="stylesheet" type="text/css" href="{% static '' %}">
  {% endblock %}

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light  sticky-top" style="background-color: black;">
    <div class="container-fluid">
      <a class="navbar-brand text-light " href="{%url 'home'%}"><b> CROWD FUNDING </b></a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {%if request.user.is_authenticated%}
          <li class="nav-item">
            <a class="nav-link text-light " href="{%url 'users:logout'%}">LOG OUT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'list_project'%}">PROJECTS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'users:userprofile'%}">PROFILE</a>
          </li>
          {%else%}
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'users:register'%}">REGISTER</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'users:login'%}">LOG IN</a>
          </li>
          {%endif%}
      </div>
      </ul>

      <a class="nav-link btn" href="{%url 'create_project'%}"
        style="background-color:#72B01D; border-radius:10px; text-decoration: none; color: #000; font-weight: 600;">CREATE
        PROJECT</a>
      <form class="d-flex" action="{%url 'search'%}" method="POST">
        {% csrf_token %}
        <input class="form-control" type="text" name="query" placeholder="Search" style="margin-left: 10px;" required />
        <input type="submit" class="btn btn-outline-light" name="Search" style="margin-left: 10px;" />
        <!--  -->
      </form>
    </div>
    </div>
  </nav>
  <div>
    {%block content%}
    <h1>HomePage</h1>
    {%endblock%}
  </div>
  <footer class="text-center fixed-bottom text-white" style="margin-top: 100px; ">

    <div class="text-center p-3 " style="background-color: #000;">
      © 2023 Copyright: Crowd Funding
    </div>
  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  
</body>

</html>

project/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
Crowd Funding
{% endblock %}

{%block content%}
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    {% for project in topRatedProjectsList %}
    <li data-target="#carouselExampleIndicators" data-slide-to={{forloop.counter0}}></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for project in topRatedProjectsList %}

    {% if forloop.first %}
    <div class="carousel-item active ">
      {% else %}
      <div class="carousel-item  ">
        {% endif %}
        <img style="width:100%;height:500px;" src="{{project.0.img.url}}">
        <div class="carousel-caption d-none d-md-block">
          <div class="d-flex justify-content-center">
            <a href="/project/project_info/{{project.0.project_id.project_id}}" style="text-decoration:none;">
              <h1 class="text-dark" style="text-transform: uppercase; border-radius: 5px; background-color: white; box-shadow: 2px 2px 15px 15px rgba(0, 0, 0, 0.034); height: fit-content; width: fit-content;">{{project.0.project_id.title}}</h1>
            </a>
          </div>

        </div>
      </div>
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only"></span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only"></span>
    </a>
  </div>
  <div class="container bg-light " style="margin-top:40px ; border-radius: 40px; padding: 10px;">
    <div class="text-center " style="font-size: 50px; font-weight: 600; color: #000; text-transform: uppercase;"> Latest
      Projects</div>
    <div class="row d-flex justify-content-center">
      {% for project in latestProjectsList %}
      <div class="card col-md-3" style="border-radius:20px ; padding: 5px; margin: 5px;">
        {% if project.0.img %}
        {% load static %}
        <a href="/project/project_info/{{project.0.project_id.project_id}}"
          style="text-decoration:none;">
          <img class="card-img-top w-100" height="200" src="{{project.0.img.url}}" alt="Card image"
            style="border-radius: 15px;">
        </a>
        {% else %}
        <img class="card-img-top w-100" height="200" src="" alt="Not Found ">
        {% endif %}
        <div class="card-body">
          <h4 class="card-title">{{project.0.project_id.title}}</h4>
          <p class="card-text">Total target : <span class="text-success">{{project.0.project_id.total_target}} $</span>
          </p>
          <p class="card-text">
          <Details> <span class="text-success">{{project.0.project_id.details}} </span></Details>
          </p>
          <p class="card-text">Start Date : <span class="text-success">{{project.0.project_id.start_date}} </span>
          </p>
          <p class="card-text">End Date : <span class="text-success">{{project.0.project_id.end_date}}</span></p>
        </div>

      </div>
      {%endfor%}
    </div>
  </div>
  <div class="container " style="margin-top:40px ; border-radius: 40px; background-color:#72B01D ; padding: 10px;">
    <div class="text-center" style="font-size: 50px; font-weight: 600; color: #000; text-transform: uppercase;">
      Featured Projects</div>
    <div class="row d-flex justify-content-center">
      {% for project in featuredProjectsList %}
      <div class="card col-md-3" style="border-radius:20px ; padding: 5px; margin: 5px; background-color: #000;">
        {% if project.0.img %}
        {% load static %}
        <a href="/project/project_info/{{project.0.project_id.project_id}}"
          style="text-decoration:none;">
          <img class="card-img-top w-100" height="200" src="{{project.0.img.url}}" alt="Card image"
            style="border-radius: 15px;">
        </a> {% else %}
        <img class="card-img-top w-100" height="200" src="" alt="Not Found ">
        {% endif %}
        <div class="card-body" style="color: white;">
          <h4 class="card-title">{{project.0.project_id.title}}</h4>
          <p class="card-text">Total target : <span style="color: #72B01D;">{{project.0.project_id.total_target}}
              $</span>
          </p>
          <p class="card-text">
          <Details> <span style="color: #72B01D;">{{project.0.project_id.details}} </span></Details>
          </p>
          <p class="card-text">Start Date : <span style="color: #72B01D;">{{project.0.project_id.start_date}} </span>
          </p>
          <p class="card-text">End Date : <span style="color: #72B01D;">{{project.0.project_id.end_date}}</span></p>
        </div>

      </div>
      {%endfor%}
    </div>
  </div>

  <div class="container bg-light " style="margin-top:40px ; border-radius: 40px; padding: 10px; margin-bottom: 100px; ">
    <div class="text-center " style="font-size: 50px; font-weight: 600; color: #000; text-transform: uppercase;">
      Categories</div>
    <div class="row mt-2 mb-5">
      {% for category in categories %}
      <div class="col-md-3 text-center text-dark">
        <a href="project/projectlist/{{category.category_id}}" class="text-dark" style="text-decoration: none; ">
          <h3 class="badge"
            style="size: 40px; font-size: 40px; border-radius: 20px; background-color:#72B01D ;color: #000; text-transform: uppercase;">
            {{category.category_name}}
          </h3>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>

</div>
{%endblock%}