project/project/urls.py
# from django.contrib import admin
# from django.urls import path, include
from django.contrib import admin
from django.urls import path , include,re_path
from django.conf import settings
from django.conf.urls.static import static

from fundproject.views import home 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', home,name='home'),
    path('project/', include('fundproject.urls')),
    path('fundapi/', include('fundapi.urls')),
    re_path('^', include('django.contrib.auth.urls')),


]
# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import include, path, re_path


from users.views import register, user_login, activate, index
from django.conf import settings
from django.conf.urls.static import static
from users import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetConfirmView
from .views import userprofile
from rest_framework import routers
from .views import usersListView
app_name = 'users'
router = routers.DefaultRouter()
router.register(r'usersListView', usersListView)

urlpatterns = [

    path('register/', views.register , name='register'),
    path('activate/<uidb64>/<time>',views.activate, name='activate'),
    path('login/', views.user_login , name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('userprofile', views.userprofile  , name="userprofile"),
    path('deleteprofile/<int:id>' , views.deleteprofile , name="deleteprofile"),
    path('editprofile/<int:id>' , views.editprofile , name="editprofile"),
    path('userproject/<int:id>' , views.userproject , name="userproject"),
    path('userdonation/<int:id>' , views.userdonation , name="userdonation"),
    path('users', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('logout/',views.logout_view,name='logout'),
    #  path('profile',views.user_profile,name="profile"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_reset/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_reset/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset/password_change.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset/password_reset_form.html'), name='password_reset'),


    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset/password_reset_complete.html'),
     name='password_reset_complete'),

    re_path('^', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, UserManager, PermissionsMixin
from django.core.validators import RegexValidator
from django.contrib.auth.models import BaseUserManager
from django.utils.translation import gettext_lazy as _
# Create your models here.
class CustomAccountManager(BaseUserManager):
    def create_user(self, email, username, first_name, password, **other_fields):
        if not email:
            raise ValueError(_('Please provide an email address'))
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, first_name=first_name, **other_fields)
        user.set_password(password)
        user.save()
        return user


    def create_superuser(self, email, username, first_name, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        if other_fields.get('is_staff') is not True:
            raise ValueError(_('Please assign is_staff=True for superuser'))
        if other_fields.get('is_superuser') is not True:
            raise ValueError(_('Please assign is_superuser=True for superuser'))
        return self.create_user(email, username, first_name, password, **other_fields)

class Users(AbstractBaseUser, PermissionsMixin):
  #  id= models.AutoField(primary_key=True)
    phone_regex = RegexValidator(regex=r'^01[1|0|2|5][0-9]{8}$',message='phone must be an egyptian phone number...')
    username = models.CharField(verbose_name="user_name" ,null=False, max_length=50)
    first_name = models.CharField(verbose_name="first_name" ,null=False, max_length=50)
    last_name = models.CharField(verbose_name= "last_name" ,null=False, max_length=50)
    email = models.EmailField(verbose_name='email', null=False, max_length=150,unique=True)
    phone = models.CharField(verbose_name="phone",null=True,validators=[phone_regex],max_length=14)
    photo = models.ImageField(verbose_name="photo",upload_to='images')
    is_active = models.BooleanField(default=False)

    #other fields
    date_birth = models.DateField(null=True)
    facebook_link = models.URLField(null=True)
    country = models.CharField(max_length=50, null=True)


    # is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','first_name','last_name','phone']

    objects = CustomAccountManager()

project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import Users
from django.contrib.auth import authenticate




class RegistraionForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = Users
        fields = ('email','username','first_name','last_name','phone','photo','password1','password2')

#================================================================================================
class LoginForm(forms.ModelForm):
    password = forms.CharField(label='password',widget=forms.PasswordInput)
    class Meta:
        model = Users
        fields = ('email','password', 'is_active')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email,password=password):
                raise forms.ValidationError('invalid login data...')

#===================================================================================================

class DateInput(forms.DateInput):
    input_type = 'date'


class UpdateUserForm(forms.ModelForm):
    date_birth = forms.DateField(required=False,widget=DateInput())
    photo = forms.ImageField(required=False,widget=forms.FileInput)
    facebook_link = forms.URLField(required=False)
    country = forms.CharField(required=False)
    class Meta:
        model = Users
        fields = ('first_name','last_name','phone','photo','date_birth','facebook_link','country')

    def clean_country(self):
        if self.is_valid():
            country = self.cleaned_data['country']
            if country:
                return country
            else :
                return None


    def clean_facebook_link(self):
        if self.is_valid():
            facebook_link = self.cleaned_data['facebook_link']
            if facebook_link:
                return facebook_link
            else :
                return None


    def clean_date_birth(self):
        if self.is_valid():
            date_birth = self.cleaned_data['date_birth']
            if date_birth:
                return date_birth
            else :
                return None

project/users/views.py
from users.forms import RegistraionForm, LoginForm, UpdateUserForm
from django.shortcuts import render, redirect, reverse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from users.models import Users
import datetime
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .serializers import usersSerializer
from rest_framework import permissions
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from fundproject.models import Project , Donation


@api_view(['GET', 'DELETE', 'PUT'])
def userView(request, id):
    try:
        user = Users.objects.get(id=id)
    except Users.DoesNotExist:
        return Response("HTTP_404_NOT_FOUND")
    if request.method == 'DELETE':
        user.delete()
        return Response({'msg', f'user deleted'})
    elif request.method == 'GET':
        res = usersSerializer(user, context={'request': request})
        return (res.data)
    elif request.method == 'PUT':
        req_update = usersSerializer(user, data=request.data, context={'request': request})
        if req_update.is_valid():
            req_update.save()
            return Response(req_update.data)
        else:
            return Response(req_update.errors)
    else:
        return Response({'msg': 'None'})


class usersListView(viewsets.ModelViewSet):
    queryset = Users.objects.all()
    serializer_class = usersSerializer


# Create your views here.
def register(request):
    context = {}
    if request.method == 'POST':
        form = RegistraionForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            print(user)
            send_email(
                user,
                get_current_site(request),
                form.cleaned_data.get("email"),
                "users/account_activation.html",
                "Activate your account.",
            )
            return render(request, "users/sending_email.html", {"active_code": -1})
        else:
            context["form"] = form
    else:
        form = RegistraionForm()
    return render(request, 'users/new-register.html', {'form': form})


def send_email(user, current_site, email, email_body, email_subject):
    mail_subject = email_subject
    message = render_to_string(
        email_body,
        {
            "user": user,
            "domain": current_site.domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "time": urlsafe_base64_encode(force_bytes(datetime.datetime.now())),
        },
    )
    to_email = email
    email = EmailMessage(mail_subject, message, to=[to_email])
    email.send()


def activate(request, uidb64, time):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        print("user id : ", uid)
        time_sent = force_str(urlsafe_base64_decode(time))
        user = Users.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError):
        user = None
    if user is not None:
        if user.is_active == False:
            email_sent_at = time_sent
            date_diffrince = (
                                     datetime.datetime.now()
                                     - datetime.datetime.strptime(email_sent_at,
                                                                  "%Y-%m-%d %H:%M:%S.%f")
                             ).seconds / 60

            if date_diffrince < (24 * 60):
                user.is_active = True
                user.save()
                return render(
                    request, "users/sending_email.html", {"active_code": 1}
                )
            else:
                current_site = get_current_site(request)
                email = user.email
                send_email(
                    user,
                    current_site,
                    email,
                    "users/account_activation.html",
                    "Activate your account.",
                )
                return render(
                    request, "users/sending_email.html", {"active_code": 0}
                )
        else:
            return render(request, "users/sending_email.html", {"active_code": 2})
    else:
        return render(request, "users/sending_email.html", {"active_code": 3})


def user_login(request):
    # if request.user.is_authenticated:
    #     return redirect('/')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(email=Users.objects.get(email=email), password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    print(user)
                    request.session['usernew']=user.first_name
                    request.session['id']=user.id
                    return render(request, "users/index.html")
            # else:
            #     messages.info(request,'invalid login data...')
    else:
        form = LoginForm()

    return render(request, 'users/new-login.html', {'form': form})


@login_required(login_url='/login')
def index(request):
    context = {
        "user": request.username
    }
    return render(request, "users/index.html", context)


# # #####
def logout_view(request):
    request.session.clear()
    logout(request)
    return redirect('/login')


@login_required(login_url='/login')
def userprofile(request):
    if not request.user.is_authenticated:
        return redirect(reverse("users:login"))
    return render(request, "users/userprofile.html")


@login_required(login_url='/login')
def deleteprofile(request, id):
    user = Users.objects.get(id=id)
    if request.method == 'POST':
        if user.project_set.exists():
            return redirect(reverse("users:userproject", args=[id]))

        else:
            user.delete()
            logout(request)
            return redirect('home')
    return render(request, "users/deleteprofile.html")

@login_required(login_url='/login')
def editprofile(request, id):
    user = Users.objects.get(id=id)
    form = UpdateUserForm(request.POST or None, request.FILES or None, instance=user)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse("users:userprofile"))
    else:
        form = UpdateUserForm(
            initial={
                "first_name": user.first_name,
                "last_name": user.last_name,
                "phone": user.phone,
                "date_birth": user.date_birth,
                "facebook_link": user.facebook_link,
                "country": user.country,
            }
        )

    return render(request, "users/editprofile.html", {"form": form})

# def editprofile(request,id):
#     form = UpdateUserForm(request.POST, request.FILES, instance=request.user)
#     if request.method == 'POST':
#         if form.is_valid():
#             print("photo from form is :", form.cleaned_data["photo"])
#             request.user.photo = form.cleaned_data["photo"]
#             form.save()
#             return redirect(reverse("users:userprofile"))
#         else:
#             form = UpdateUserForm(
#                 initial={
#                     "first_name": request.user.first_name,
#                     "last_name": request.user.last_name,
#                     "phone": request.user.phone,
#                     "date_birth": request.user.date_birth,
#                     "facebook_link": request.user.facebook_link,
#                     "country": request.user.country,

#                 }
#             )
#         # context={"form": form}
#     return render(request, "users/editprofile.html", {"form": form})


@login_required(login_url='/login')
def userproject(request, id):
    user = Users.objects.get(id=id)
    projects = Project.objects.filter(
        user_id=user)  
    context = {
        "user": user,
        "projects": projects
    }

    return render(request, "users/userproject.html" ,context)


@login_required(login_url='/login')
def userdonation(request , id):
     user = Users.objects.get(id=id)
     donations = Donation.objects.filter(user_id = user)
     context = {
         "user": user,
         "donations": donations
     }
     return render(request, "users/userdonation.html" , context)

project/users/templates/users/account_activation.html
{% autoescape off %}
Hi {{ user.first_name }} {{ user.last_name }},
Please click on the link to confirm your registration,http://{{ domain }}{% url 'users:activate' uidb64=uid time=time %}
{% endautoescape %}

project/users/templates/users/deleteprofile.html
{%extends  'base.html'%}
{% load static%}
{% block Title %} Confirmation {% endblock %}
{% block head-css %}
<link rel="stylesheet" href="{% static 'css/usersindex.css' %}">
<link rel="stylesheet" href="{% static 'css/deleteconfirm.css' %}"/>
{% endblock %}
{% block content%}
<div class="sidebar" style="width:15%">
    <br/>
    <br/>
    <br/>
    <a href="{% url 'users:userprofile' %}" class="w3-bar-item w3-button">Profile</a> <br> <br>
    <a href="{%url 'users:userproject' user.id %}" class="w3-bar-item w3-button">Projects </a> <br> <br>
    <a href="{%url 'users:userdonation' user.id %}" class="w3-bar-item w3-button">Donations</a> <br> <br>
    <a href="{%url 'users:logout' %}" class="w3-bar-item w3-button">Log out</a> <br> <br>
</div>
<div class="container" style="margin-left:20%">
    <form method="post" action="">
        {% csrf_token %}
        <div class="container">
            <h1>Delete Account</h1> <br>
            <p>Are you sure you want to delete?</p><br>
            <input class="btn btn-danger" type="submit" value="Yes"/>
            <a href="{%url 'users:userprofile' %}">
                <div class="btn btn-primary">Cancel</div>
            </a>
        </div>
    </form>
</div>
{% endblock%}

project/users/templates/users/editprofile.html
{%extends  'base.html'%}
{% block Title %} Edit {% endblock %}
{% load bootstrap4 %}
{% block head-css %}
{% load static %}
 <link rel="stylesheet" href="{% static 'css/usersindex.css' %}">
{% endblock %}
{% block content %}
<div class="sidebar" style="width:15%">
    <br/>
    <br/>
    <br/>
    <a href="{% url 'users:userprofile' %}" class="w3-bar-item w3-button">Profile</a> <br> <br>
    <a href="{%url 'users:userproject' user.id %}" class="w3-bar-item w3-button">Projects </a> <br> <br>
    <a href="{%url 'users:userdonation' user.id %}" class="w3-bar-item w3-button">Donations</a> <br> <br>
    <a href="{%url 'users:logout' %}" class="w3-bar-item w3-button">Log out</a> <br> <br>
</div>
<div class="container" style="margin-left:20%">
<form method="post" enctype="multipart/form-data">
    <br/>
    <br/>
    {%csrf_token%}
    {% bootstrap_form form %}

    <br>
    <button type="submit" class="btn btn-dark">
        Update
    </button>
</form>
    </div>

{% endblock %}

project/users/templates/users/index.html
{%extends 'base.html' %}
{% load static %}


    {% block head-css  %}
       <link rel="stylesheet" href="{% static 'css/usersindex.css' %}">
    {% endblock %}
<!--     <link rel="stylesheet" href="{% static 'css/usersindex.css' %}">-->
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"-->
<!--          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
<!--    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"-->
<!--          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">-->

    {% block Title %} Crowd Funding {% endblock %}


{% block content %}

<div class="sidebar" style="width:15%">
    <br/>
    <br/>
    <br/>
    <a href="{% url 'users:userprofile' %}" class="w3-bar-item w3-button">Profile</a> <br> <br>
    <a href="{%url 'users:userproject' user.id %}" class="w3-bar-item w3-button">Projects </a> <br> <br>
    <a href="{%url 'users:userdonation' user.id %}" class="w3-bar-item w3-button">Donations</a> <br> <br>
    <a href="{%url 'users:logout' %}" class="w3-bar-item w3-button">Log out</a> <br> <br>
</div>


<div style="margin-left:20%">
    <br>
    <br>
         <h1 style="color:green">  Welcome {{request.session.usernew}}</h1>
<!--         <h1 style="color:green">  Welcome {{request.session.id}}</h1>-->
    <br/>
    

</div>
 {% endblock %}

project/users/templates/users/new-login.html
{% extends "users/base.html" %}
{% block title %} Log in {% endblock title %}
{% block content %}
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h2 id="form-title">LOGIN</h2>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							{{form.email}}
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

							{{form.password}}
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>
				</div>

				<!--{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}-->
				{{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'users:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Forget your password? <a href="{% url 'users:password_reset' %}" class="ml-2">Reset Password</a>
					</div>

				</div>
			</div>
		</div>
	</div>

<script>
		/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Email..';
		form_fields[2].placeholder='Enter password...';

		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
{% endblock content %}

project/users/templates/users/sending_email.html
{% extends "users/base.html" %}
{% block title %}Account Activation{% endblock %}
{% block content %}

<div class="container" style="margin-top: 30px;">
    {%if active_code == 1%}
    <h3>Thank you for your email confirmation. Now you can login your account.</h3>
    <div class="logoin">
        <a href="{%url 'users:login' %}" class="btn btn-outline-success  active" role="button"
        aria-pressed="true">Login</a>
    </div>
    {%elif active_code == 0 %}
    <h3>Activation link is valid for 24 hours only a new link has been sent to your email...</h3>
    {%elif active_code == -1 %}
    <h3>Please confirm your email address to complete the registration</h3>
    {%else %}
    <h3>Activation link is invalid!</h3>
    {%endif%}
</div>







{% endblock content %}

project/users/templates/users/sending_email_on_delete.html
{% autoescape off %}
Hi {{ user.first_name }} {{ user.last_name }},
Please click on the link to delete your account,http://{{ domain }}{% url 'users:account_delete' uidb64=uid time=time %}
{% endautoescape %}

project/users/templates/users/userdonation.html
{%extends  'base.html'%}
{% load static %}
{% block Title %} Donations {% endblock %}
{% block head-css %}
<link rel="stylesheet" href="{% static 'css/usersindex.css' %}">
{% endblock %}
{% block content %}
<div class="sidebar" style="width:15%">
    <br/>
    <br/>
    <br/>
    <a href="{% url 'users:userprofile' %}" class="w3-bar-item w3-button">Profile</a> <br> <br>
    <a href="{%url 'users:userproject' user.id %}" class="w3-bar-item w3-button">Projects </a> <br> <br>
    <a href="{%url 'users:userdonation' user.id %}" class="w3-bar-item w3-button">Donations</a> <br> <br>
    <a href="{%url 'users:logout' %}" class="w3-bar-item w3-button">Log out</a> <br> <br>
</div>
<div class="container" style="margin-left:20%">
    <br>
    <h2> Hy! {{request.user.username}}</h2>
    <br>
    <div class="container">
        {% if donations.count == 0 %}
        <div style="color:red"> Unfortunately, you don't have any donation</div>
        {% else %}
        {%for donation in donations %}
        <span style="color:green; font-weight: bold; ">Number: </span> {{ forloop.counter }} <br>
        <span style="color:green; font-weight: bold; ">Donation Value:  </span> {{ donation.donation_value }} <br>
        <span style="color:green; font-weight: bold; ">Project Title:  </span> {{ donation.project_id.title }}<br>
        <br>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

project/users/templates/users/userprofile.html
{%extends  'base.html'%}

{% load static%}
{% block Title %} Profile {% endblock %}
{% block head-css %}
 <link rel="stylesheet" href="{% static 'css/usersindex.css' %}">
<link rel="stylesheet" href="{% static 'css/userprofile.css' %}">
{% endblock %}
{% block content %}
<div class="sidebar" style="width:15%">
    <br/>
    <br/>
    <br/>
    <a href="{% url 'users:userprofile' %}" class="w3-bar-item w3-button">Profile</a> <br> <br>
    <a href="{%url 'users:userproject' user.id %}" class="w3-bar-item w3-button">Projects </a> <br> <br>
    <a href="{%url 'users:userdonation' user.id %}" class="w3-bar-item w3-button">Donations</a> <br> <br>
    <a href="{%url 'users:logout' %}" class="w3-bar-item w3-button">Log out</a> <br> <br>
</div>
<div class="card mb-4 border-0" style="margin-left:20% ;">
    <br/>
    <br/>
    <img class="img-radius profile-image" src="{{request.user.photo.url}}" alt="Card image cap" style="width:100%; max-width: 300px;height: 100%;max-height: 300px;">
    <div class="card-body">
        <h5 class="card-title username" style="font-size: 2em; color: #72B01D;">{{request.user.username}}</h5>
        <p class="card-text"><span class="data">First Name: </span><span>{{request.user.first_name}}</span></p>
        <p class="card-text"><span class="data">Last Name: </span><span>{{request.user.last_name}}</span></p>
        <p class="card-text"><span class="data">Email: </span><span>{{request.user.email}}</span></p>
        <p class="card-text"><span class="data">Phone: </span><span>{{request.user.phone}}</span></p>
        <p class="card-text"><span class="data">Country: </span><span>{{request.user.country}}</span></p>
        <p class="card-text">
            <br/>
            <br/>
            <a href="{% url 'users:deleteprofile' user.id %}" class="btn btn-outline-danger  active" role="button"
               aria-pressed="true">Delete Account</a>
            <a href="{%url 'users:editprofile' user.id %}" class="btn btn-outline-success  active" role="button"
               aria-pressed="true">Edit Account</a>
        </p>
    </div>
</div>
{% endblock %}

project/users/templates/users/userproject.html
{%extends  'base.html'%}
{% load static %}
{% block Title %} Projects {% endblock %}
{% block head-css %}
<link rel="stylesheet" href="{% static 'css/usersindex.css' %}">
{% endblock %}
{% block content %}
<div class="sidebar" style="width:15%">
    <br/>
    <br/>
    <br/>
    <a href="{% url 'users:userprofile' %}" class="w3-bar-item w3-button">Profile</a> <br> <br>
    <a href="{%url 'users:userproject' user.id %}" class="w3-bar-item w3-button">Projects </a> <br> <br>
    <a href="{%url 'users:userdonation' user.id %}" class="w3-bar-item w3-button">Donations</a> <br> <br>
    <a href="{%url 'users:logout' %}" class="w3-bar-item w3-button">Log out</a> <br> <br>
</div>
<div class="container" style="margin-left:20%">
    <br>
    <h2> Hy! {{request.user.username}}</h2>
    <!--    <h6 >Your No. of projects is <span style="color:green">{{ projects.count }} </span> </h6>-->
    <div class="container">
        {% if projects.count == 0 %}
        <div style="color:red"> Unfortunately, you don't have any project</div>
        {% else %}

        {%for project in projects %}
        <div>
          <br>
          
          <span style="color:green; font-weight: bold; ">Title:  </span> {{ project.title }} <br>
          <span style="color:green; font-weight: bold;">Start Date:  </span> {{ project.start_date }} <br>
          <span style="color:green; font-weight: bold;" >End Date: </span>  {{ project.end_date }} <br>
          <a class="btn-danger" href="{% url 'cancel_project' project.project_id %}">Cancel project</a>
          <br>
        </div>
        {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock %}